# Project information
site_name: 日本語っぽい
site_url: https://arcelopera.github.io/NihongoPoi
site_description: Road to 一級.
site_author: ArceLopera

# Repository
repo_url: https://github.com/ArceLopera/NihongoPoi
repo_name: ArceLopera/NihongoPoi
edit_uri: "" #disables edit button

# Copyright
copyright: Copyright &copy; 2023

# Social media
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ArceLopera
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/carlos-arcelopera
    - icon: fontawesome/brands/github
      link: https://github.com/ArceLopera
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/
    - icon: fontawesome/solid/paper-plane
      link: mailto:arcelopera.carlos@gmail.com

# Configuration
theme:
  name: material
  logo: Images/japan.png
  favicon: Images/japan.png
  palette:
    
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

  features:
    - navigation.tabs
    - navigation.expand
  icon:
    repo: fontawesome/brands/github

# Extensions
markdown_extensions:
  - admonition # alerts
  - pymdownx.details #  collapsible alerts
  - pymdownx.superfences # nest code and content inside alerts
  - attr_list # add HTML and CSS to Markdown elements
  - pymdownx.inlinehilite # inline code highlights
  - pymdownx.keys # show keystroke symbols
  - pymdownx.snippets # insert content from other files
  - footnotes
  - def_list
  - pymdownx.arithmatex: # mathjax
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.highlight:
      use_pygments: true
  - toc:
      toc_depth: 4

# Plugins
plugins:
  - search


# Extra JS
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Page tree
nav:
  - ホーム: index.md
  - 文法:
    - ですーますVSだーである: ./N3/desu_masuVSda_dearu.md
    - 連用中止形: ./N3/suspendedForm.md
    - 表現の違い: ./N3/grammar1.md
    - 接続詞: ./N3/grammar2.md
    - 引用・文型: ./N3/grammar3.md
    - グラフの読み方: ./N3/grammar4.md
    - 敬語:
      - Basic: ./N3/keigo-intro.md
      - 尊敬語: ./N3/sonkeigo.md
      - 謙譲語: ./N3/kenjougo.md
      - Honorific Verbs: ./N3/keigo-verbs.md
      - Honorific Nouns: ./N3/keigo-nouns.md
      - 会話のスタイル: ./N3/keigo-expressions.md
      - 例: ./N3/keigo-kaiwa.md
    - N5:
      - Each:
        - とき: ./N5/Grammar/toki.md
    - N4:
      - Each:
        - 間: ./N4/Grammar/aida.md
        - 間に: ./N4/Grammar/aidani.md
        - ところ: ./N4/Grammar/tokoro.md
    - N3:
      - Each:
        - うちに: ./N3/Grammar/uchini.md
        - てからないと: ./N3/Grammar/tekaradenaito.md
        - によって・による: ./N3/Grammar/niyotte.md
        - によると・によれば: ./N3/Grammar/niyoruto.md
        - にとって: ./N3/Grammar/nitotte.md
        - たびに: ./N3/Grammar/tabini.md
        - ほど: ./N3/Grammar/hodo.md
        - ば～ほど: ./N3/Grammar/bahodo.md
        - ほど～ない: ./N3/Grammar/hodonai.md
        - とおりに: ./N3/Grammar/toorini.md
        - くらい: ./N3/Grammar/kurai.md
  - 語彙:
    - 自己紹介: ./N4/presentation.md
    - 副詞: 
      - N5: ./N5/adverbsN5.md
      - N4: ./N4/adverbsN4.md
      - N3: 
        - All: ./N3/AdverbN3/adverbsN3.md
        - Each:
          - あまり: ./N3/AdverbN3/amari.md
          - あまりにも: ./N3/AdverbN3/amarinimo.md
          - 別に～ない: ./N3/AdverbN3/betsuninai.md
          - どんなに～ても: ./N3/AdverbN3/donnanitemo.md
          - どうしても: ./N3/AdverbN3/doushitemo.md
          - 再び: ./N3/AdverbN3/futatabi.md
          - ふと: ./N3/AdverbN3/futo.md
          - 一度に: ./N3/AdverbN3/ichidoni.md
          - 意外: ./N3/AdverbN3/igai.md
          - いくら～ても: ./N3/AdverbN3/ikuratemo.md
          - 今に: ./N3/AdverbN3/imani.md
          - 今にも: ./N3/AdverbN3/imanimo.md
          - 一種: ./N3/AdverbN3/isshu.md
          - 一層: ./N3/AdverbN3/issou.md
          - 一体: ./N3/AdverbN3/ittai.md
          - か何か: ./N3/AdverbN3/kanika.md
          - 結局: ./N3/AdverbN3/kekkyoku.md
          - 決して～ない: ./N3/AdverbN3/kesshite_nai.md
          - 急に: ./N3/AdverbN3/kyuuni.md
          - 万一: ./N3/AdverbN3/manichi.md
          - まるで: ./N3/AdverbN3/marude.md
          - つい: ./N3/AdverbN3/tsui.md
          - ついに: ./N3/AdverbN3/tsuini.md
          - ついでに: ./N3/AdverbN3/tsuideni.md
      - N2: ./N2/adverbsN2.md
      - N1: ./N1/adverbsN1.md
  - テスト:
    - N4: ./N4/test.md
    - N3: ./N3/test.md
    - N2: ./N2/test.md
  - 漢字:
    - N3:
      - All: ./N3/Kanji/all.md
      - 余: ./N3/Kanji/680.md

